# Generated by Django 4.0.4 on 2022-04-14 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_placeimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placeimage',
            old_name='order',
            new_name='order_number',
        ),
    ]
