# Generated by Django 4.0.4 on 2022-04-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_rename_order_placeimage_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='order_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
