# Generated by Django 4.0.4 on 2022-04-14 03:47

from django.db import migrations, models
import places.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_placeimage_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ('order_number',), 'verbose_name': 'фотография места', 'verbose_name_plural': 'фотографии места'},
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=models.ImageField(upload_to=places.models.place_image_path, verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='order_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='позиция'),
        ),
    ]
